[package]
name = "grafx_engine"
version = "0.1.0"
authors = ["bsoft"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
freetype-rs = "0.29.0"
gl = "0.14.0"
glutin = "0.28.0"
nuid = "~0.2"